---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

This line is from Rstudio

- Line from RStudio

Both of us had to set up git before we started since neither of us had completed the setup earlier this week.

Cloning the repository was simple once everything was set up, and we didn't have any trouble viewing the files.

We entered and attempted to commit the changes. Carolyn found she had to log in to gitbash first before the commits were able to get through. 

We then pushed the files, and Luke had to merge the changes in order to get his edits to got through.

Afterwards we both pulled from the repository to make sure the changes went through, and checked the repository itself. There were no issues found.


